//
//  Quotes.swift
//  Elara
//
//  Created by Milind Contractor on 5/7/25.
//

import Foundation

struct Quote: Identifiable, Codable, Equatable {
    var id: UUID = UUID()
    var quote: String
    var author: String
    var date: Date = Date()
}

let motivationalQuotes: [Quote] = [
    Quote(quote: "You don't have to see the whole staircase, just take the first step.", author: "Martin Luther King Jr."),
    Quote(quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe"),
    Quote(quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney"),
    Quote(quote: "Concentrate all your thoughts upon the work in hand. The sun's rays do not burn until brought to a focus.", author: "Alexander Graham Bell"),
    Quote(quote: "It's not that I'm so smart, it's just that I stay with problems longer.", author: "Albert Einstein"),
    Quote(quote: "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", author: "Stephen King"),
    Quote(quote: "A year from now you may wish you had started today.", author: "Karen Lamb"),
    Quote(quote: "If you spend too much time thinking about a thing, you'll never get it done.", author: "Bruce Lee"),
    Quote(quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau"),
    Quote(quote: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln"),
    Quote(quote: "Do the hard jobs first. The easy jobs will take care of themselves.", author: "Dale Carnegie"),
    Quote(quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky"),
    Quote(quote: "I never dream of success. I work for it.", author: "Estee Lauder"),
    Quote(quote: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun"),
    Quote(quote: "You can't cross the sea merely by standing and staring at the water.", author: "Rabindranath Tagore"),
    Quote(quote: "Don't count the days, make the days count.", author: "Muhammad Ali"),
    Quote(quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill"),
    Quote(quote: "Work gives you meaning and purpose and life is empty without it.", author: "Stephen Hawking"),
    Quote(quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt"),
    Quote(quote: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius"),
    Quote(quote: "The only way to do great work is to love what you do.", author: "Steve Jobs"),
    Quote(quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson"),
    Quote(quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt"),
    Quote(quote: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle"),
    Quote(quote: "The secret of getting ahead is getting started.", author: "Mark Twain"),
    Quote(quote: "Your limitation—it's only your imagination.", author: "Anonymous"),
    Quote(quote: "Great things never come from comfort zones.", author: "Anonymous"),
    Quote(quote: "Dream it. Wish it. Do it.", author: "Anonymous"),
    Quote(quote: "Success doesn't just find you. You have to go out and get it.", author: "Anonymous"),
    Quote(quote: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Anonymous"),
    Quote(quote: "Don't stop when you're tired. Stop when you're done.", author: "Anonymous"),
    Quote(quote: "Wake up with determination. Go to bed with satisfaction.", author: "Anonymous"),
    Quote(quote: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery"),
    Quote(quote: "Little things make big days.", author: "Anonymous"),
    Quote(quote: "It's going to be hard, but hard does not mean impossible.", author: "Anonymous"),
    Quote(quote: "Don't wait for opportunity. Create it.", author: "Anonymous"),
    Quote(quote: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", author: "Anonymous"),
    Quote(quote: "The key to success is to focus on goals, not obstacles.", author: "Anonymous"),
    Quote(quote: "Dream bigger. Do bigger.", author: "Anonymous"),
    Quote(quote: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller"),
    Quote(quote: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson"),
    Quote(quote: "Push yourself, because no one else is going to do it for you.", author: "Anonymous"),
    Quote(quote: "The only impossible journey is the one you never begin.", author: "Tony Robbins"),
    Quote(quote: "In the middle of difficulty lies opportunity.", author: "Albert Einstein"),
    Quote(quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius"),
    Quote(quote: "Everything you've ever wanted is on the other side of fear.", author: "George Addair"),
    Quote(quote: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson"),
    Quote(quote: "Champions don't become champions in the ring. They become champions in their training.", author: "Anonymous"),
    Quote(quote: "The successful warrior is the average man with laser-like focus.", author: "Bruce Lee"),
    Quote(quote: "Opportunities don't happen. You create them.", author: "Chris Grosser"),
    Quote(quote: "Try not to become a person of success, but rather try to become a person of value.", author: "Albert Einstein"),
    Quote(quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson"),
    Quote(quote: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett"),
    Quote(quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson"),
    Quote(quote: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau"),
    Quote(quote: "When you have a dream, you've got to grab it and never let go.", author: "Carol Burnett"),
    Quote(quote: "Nothing is impossible. The word itself says 'I'm possible!'", author: "Audrey Hepburn"),
    Quote(quote: "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", author: "Aristotle"),
    Quote(quote: "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.", author: "Jesus"),
    Quote(quote: "The only thing worse than starting something and failing... is not starting something.", author: "Seth Godin"),
    Quote(quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson"),
    Quote(quote: "If you really look closely, most overnight successes took a long time.", author: "Steve Jobs"),
    Quote(quote: "The way I see it, if you want the rainbow, you gotta put up with the rain.", author: "Dolly Parton"),
    Quote(quote: "Don't limit yourself. Many people limit themselves to what they think they can do.", author: "Mary Kay Ash"),
    Quote(quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde"),
    Quote(quote: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey"),
    Quote(quote: "Every child is an artist. The problem is how to remain an artist once he grows up.", author: "Pablo Picasso"),
    Quote(quote: "You can never cross the ocean until you have the courage to lose sight of the shore.", author: "Christopher Columbus"),
    Quote(quote: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou"),
    Quote(quote: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford"),
    Quote(quote: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain"),
    Quote(quote: "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", author: "Johann Wolfgang von Goethe"),
    Quote(quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb"),
    Quote(quote: "An unexamined life is not worth living.", author: "Socrates"),
    Quote(quote: "Eighty percent of success is showing up.", author: "Woody Allen"),
    Quote(quote: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs"),
    Quote(quote: "Winning isn't everything, but wanting to win is.", author: "Vince Lombardi"),
    Quote(quote: "I am not afraid of death, I just don't want to be there when it happens.", author: "Woody Allen"),
    Quote(quote: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart"),
    Quote(quote: "Life is what happens to you while you're busy making other plans.", author: "John Lennon"),
    Quote(quote: "The world is a book and those who do not travel read only one page.", author: "Saint Augustine"),
    Quote(quote: "Life is really simple, but we insist on making it complicated.", author: "Confucius"),
    Quote(quote: "It is not length of life, but depth of life.", author: "Ralph Waldo Emerson"),
    Quote(quote: "The purpose of our lives is to be happy.", author: "Dalai Lama"),
    Quote(quote: "Life is what we make it, always has been, always will be.", author: "Grandma Moses"),
    Quote(quote: "The only way to make sense out of change is to plunge into it, move with it, and join the dance.", author: "Alan Watts"),
    Quote(quote: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth"),
    Quote(quote: "Life is either a daring adventure or nothing at all.", author: "Helen Keller"),
    Quote(quote: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas A. Edison"),
    Quote(quote: "You have been assigned this mountain to show others it can be moved.", author: "Mel Robbins")
]
