// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Solstice",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Solstice",
            targets: ["AppModule"],
            bundleIdentifier: "com.advaitconty.ipad.solstice",
            teamIdentifier: "VYG284C3Z9",
            displayVersion: "1.2",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education
        )
    ],
    dependencies: [
        .package(url: "https://github.com/jiachenyee/forever", .branch("main"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Forever", package: "forever")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)